  #this is for 2 layer architecture  frontend and database

version: '3.9'

services:
  web:
    image: nginx:latest
    networks:
      - appnet
    ports:
      - "8081:80"
    depends_on:
      - db
  

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:





