version: '2.0'
services:
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "8090:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html   # mount your built frontend files
    depends_on:
      - backend # frontend waits for backend

  backend:
    image: node:18-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    entrypoint: ["node"]             # replaces ENTRYPOINT in image
    command: ["server.js"]           # passed as args to entrypoint
    ports:
      - "5000:5000"
    depends_on:
      - db       # backend waits for db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "3306:3306"


#build: ./frontend mean?
#build: → tells Docker Compose that it should build a custom image for this service instead of pulling one directly from Docker Hub.
#./frontend → is the path to the directory containing the Dockerfile.
#Here, ./frontend means: look for a folder named frontend in the same directory where your docker-compose.yml file is located.
#Inside that folder, Docker expects a Dockerfile.